{% set name = "zeroc-ice" %}
{% set version = "3.6.5" %}

package:
  name: "{{ name }}"
  version: "{{ version }}{{ environ.get('VERSION_SUFFIX', '') }}"

source:
  url: https://github.com/zeroc-ice/ice/archive/v{{ version }}.tar.gz
  sha256: 5c308c24c9721dd614d28cf5a5fa9ac19736f7a8ab894f9fd05fe5b9ac0be4fe
  patches:
    - omero-zeroc-linux.patch

build:
  number: 0
  script_env:
    - VERSION_SUFFIX

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - bzip2
    - expat
    - openjdk=8
    - libdb53
    - make
    - openssl
    - pip

outputs:
  - name: {{ name }}-libs
    requirements:
      run:
        - bzip2
        - expat
        - libdb53
        - openssl
    files:
      - bin/
      # - config
      - include/
      - lib/
      # - man
      - slice/
    test:
      commands:
        - dumpdb --version
        - glacier2router --version
        - icebox --version
        - iceboxadmin --version
        - icegridadmin --version
        - icegriddb --version
        - icegridnode --version
        - icegridregistry --version
        - icepatch2calc --version
        - icepatch2client --version
        - icepatch2server --version
        - icestormadmin --version
        - icestormdb --version
        - slice2cpp --version
        - slice2cs --version
        - slice2freeze --version
        - slice2freezej --version
        - slice2html --version
        - slice2java --version
        - slice2js --version
        - slice2php --version
        - slice2py --version
        - transformdb --version
  - name: {{ name }}-java
    requirements:
      run:
        - openjdk
    files:
      - share/java/
  # Python module is packaged separately to support multiple Python versions
  # without recompiling the rest of Ice

about:
  home: https://zeroc.com
  license: GNU General Public v2 (GPLv2)
  license_family: GPL2
  summary: Ice is a comprehensive RPC framework with support for Python, C++, .NET, Java, JavaScript and more.

extra:
  recipe-maintainers:
    - ome
